name: Publish
on:
  release:
    types: [published]

jobs:
  publish_to_dockerhub:
    name: Publish to Docker Hub
    runs-on: ubuntu-20.04
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare tags
        env:
          DOCKER_IMAGE: digidem/docker-android
          STABLE_MAJOR: 1
        id: tags
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          MAJOR=$(echo $VERSION | cut -d'.' -f 1)
          TAGS="$DOCKER_IMAGE:$VERSION,$DOCKER_IMAGE:$MAJOR"
          if [[ $MAJOR == $STABLE_MAJOR ]]; then
            TAGS="$TAGS,$DOCKER_IMAGE:latest"
          fi
          echo ::set-output name=tags::${TAGS}

      - name: Build & publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            ANDROID_BUILD_VERSION=29
            ANDROID_TOOLS_VERSION=29.0.3
            NDK_VERSION=21.4.7075529
            SYSTEM_IMAGE=android-28;default;x86_64
            NODE_VERSION=12.x
